In [1]:
#importing libraries

import pandas as pd
print(pd.__version__)

3.0.6

In [2]:
#load data
file_path = "../data/raw data/sales_dataset.xlsx"
df = pd.read_excel(file_path)
print(df.head(5))

              Order ID       Date     Status Fulfilment Sales Channel  \
0  171-7326790-9044369 2022-03-31    Shipped     Amazon     Amazon.in
1  171-7326790-9044369 2022-03-31    Shipped     Amazon     Amazon.in
2  171-7192082-3049169 2022-03-31  Cancelled   Merchant     Amazon.in
3  402-9467302-4929937 2022-03-31    Shipped     Amazon     Amazon.in
4  405-1392423-9557138 2022-03-31    Shipped     Amazon     Amazon.in

  ship-service-level    Style              SKU Category Size  ... currency  \
0          Expedited  JNE3614     JNE3614-KR-L    kurta    L  ...      INR
1          Expedited  JNE3294     JNE3294-KR-L    kurta    L  ...      INR
2           Standard  JNE3461     JNE3461-KR-L    kurta    L  ...      INR
3          Expedited  JNE3405  JNE3405-KR-XXXL    kurta  3XL  ...      INR
4          Expedited  JNE3068   JNE3068-KR-A-L    kurta    L  ...      INR

   Amount                      ship-city      ship-state  ship-postal-code  \
0  453.00  ARANI TIRUVANNAMALAI DISTRICT      TAMIL NADU          632317.0
1  353.00  ARANI TIRUVANNAMALAI DISTRICT      TAMIL NADU          632317.0
2  360.95  ARANI TIRUVANNAMALAI DISTRICT      TAMIL NADU          632317.0
3  449.00                      PANCHKULA         HARYANA          134116.0
4  688.00                       Tirupati  ANDHRA PRADESH          517501.0

  ship-country                                 promotion-ids    B2B  \
0           IN  IN Core Free Shipping 2015/04/08 23-48-5-108  False
1           IN  IN Core Free Shipping 2015/04/08 23-48-5-108  False
2           IN                                           NaN  False
3           IN                                           NaN  False
4           IN  IN Core Free Shipping 2015/04/08 23-48-5-108  False

  fulfilled-by Unnamed: 22
0          NaN         NaN
1          NaN         NaN
2    Easy Ship         NaN
3          NaN         NaN
4          NaN         NaN

[5 rows x 23 columns]

In [3]:
#counting rows and columns
df.shape

(128949, 23)

In [4]:
#dataset overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128949 entries, 0 to 128948
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128949 non-null  str
 1   Date                128949 non-null  datetime64[us]
 2   Status              128949 non-null  str
 3   Fulfilment          128949 non-null  str
 4   Sales Channel       128949 non-null  str
 5   ship-service-level  128949 non-null  str
 6   Style               128949 non-null  str
 7   SKU                 128949 non-null  str
 8   Category            128949 non-null  str
 9   Size                128949 non-null  str
 10  ASIN                128949 non-null  str
 11  Courier Status      122078 non-null  str
 12  Qty                 128949 non-null  int64
 13  currency            121155 non-null  str
 14  Amount              121155 non-null  float64
 15  ship-city           128916 non-null  object
 16  ship-state          128916 non-null  str
 17  ship-postal-code    128916 non-null  float64
 18  ship-country        128916 non-null  str
 19  promotion-ids       79807 non-null   str
 20  B2B                 128949 non-null  bool
 21  fulfilled-by        39270 non-null   str
 22  Unnamed: 22         79908 non-null   float64
dtypes: bool(1), datetime64[us](1), float64(3), int64(1), object(1), str(16)
memory usage: 21.8+ MB

In [5]:
#checking null counts
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6871
Qty                       0
currency               7794
Amount                 7794
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49142
B2B                       0
fulfilled-by          89679
Unnamed: 22           49041
dtype: int64

In [6]:
#printing duplicates columns
df.iloc[df.duplicated()]

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
6563,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,...,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN,NaN
18410,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,...,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN,NaN
53883,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,...,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,0.0
54511,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,...,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,0.0
61191,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,...,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN,0.0
120748,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,...,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,0.0

In [7]:
#numerical stats
numeric_stats = df[["Qty", "Amount"]].describe()
print(numeric_stats)

                 Qty         Amount
count  128949.000000  121155.000000
mean        0.904629     648.550806
std         0.314782     281.218324
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000

In [8]:
#only null columns of data 
null_counts = df.isnull().sum()
null_counts = null_counts[null_counts > 0]
print(null_counts)

Courier Status       6871
currency             7794
Amount               7794
ship-city              33
ship-state             33
ship-postal-code       33
ship-country           33
promotion-ids       49142
fulfilled-by        89679
Unnamed: 22         49041
dtype: int64

In [9]:
#DATA CLEANING----------------------------------------------------------------

In [10]:
#copying data for data cleaning
df_cleaned = df.copy()

In [11]:
#CLEANING THE COLUMNS
df_cleaned.columns = (
    df_cleaned.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[\s-]+", "_", regex=True)
)

In [12]:
#STANDARISING COLUMNS
text_columns = df_cleaned.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    df_cleaned[col] = df_cleaned[col].str.strip()

df_cleaned.head(1)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3614,JNE3614-KR-L,kurta,L,...,INR,453.0,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN

In [13]:
#STANDARISING COLUMN VALUES

df_cleaned["ship_city"] = df_cleaned["ship_city"].str.upper()
df_cleaned["ship_state"] = df_cleaned["ship_state"].str.upper()
df_cleaned["category"] = df_cleaned["category"].str.title()
df_cleaned.head(1)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3614,JNE3614-KR-L,Kurta,L,...,INR,453.0,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN

In [14]:
#deleting duplicates data
df_cleaned = df_cleaned.drop_duplicates()

In [15]:
#DELETING unneccessary COLUMNS
df_cleaned = df_cleaned.drop(
    columns = ["promotion_ids", "unnamed:_22"]
)
df_cleaned.head(1)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b,fulfilled_by
0,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3614,JNE3614-KR-L,Kurta,L,...,Shipped,1,INR,453.0,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN,False,NaN

In [16]:
df_cleaned.isnull().sum()

order_id                  0
date                      0
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       0
category                  0
size                      0
asin                      0
courier_status         6871
qty                       0
currency               7791
amount                 7791
ship_city                34
ship_state               33
ship_postal_code         33
ship_country             33
b2b                       0
fulfilled_by          89673
dtype: int64

In [17]:
#changing data type object to string
df_cleaned["ship_city"] = df_cleaned["ship_city"].astype(str)

In [18]:
#displaying null values rows
display(df_cleaned[df_cleaned["ship_city"].isna()])

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b,fulfilled_by
12713,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3567,JNE3567-KR-M,Kurta,M,...,NaN,0,INR,380.0,NaN,NaN,NaN,NaN,False,Easy Ship
12714,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,Kurta,S,...,NaN,0,INR,380.0,NaN,NaN,NaN,NaN,False,Easy Ship
18128,404-7506843-7913132,2022-04-12,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET350,SET350-KR-NP-L,Set,L,...,Shipped,1,INR,1299.0,NaN,NaN,NaN,NaN,False,Easy Ship
23107,406-4079063-8291520,2022-04-15,Cancelled,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-XXL,Kurta,XXL,...,Unshipped,1,INR,399.0,NaN,NaN,NaN,NaN,False,NaN
24663,402-8628677-0457954,2022-04-16,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0003,J0003-SET-S,Set,S,...,Shipped,1,INR,654.0,NaN,NaN,NaN,NaN,False,Easy Ship
29865,405-4927647-8064368,2022-04-19,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XS,Set,XS,...,Shipped,1,INR,1112.0,NaN,NaN,NaN,NaN,False,NaN
31829,402-4919636-4333150,2022-04-20,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE1233,JNE1233-BLUE-KR-031-XXXL,Kurta,3XL,...,Shipped,1,INR,376.0,NaN,NaN,NaN,NaN,False,Easy Ship
34326,404-9229894-8608305,2022-04-21,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,Kurta,M,...,Shipped,1,INR,442.0,NaN,NaN,NaN,NaN,False,NaN
35293,407-4532637-8415521,2022-04-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,Kurta,S,...,NaN,0,INR,380.0,NaN,NaN,NaN,NaN,False,Easy Ship
36729,402-0107720-7057168,2022-04-23,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,Shipped,1,INR,654.0,NaN,NaN,NaN,NaN,False,NaN
41367,406-4003386-8768363,2022-04-25,Shipped,Amazon,Amazon.in,Expedited,JNE3376,JNE3376-KR-M,Kurta,M,...,Shipped,1,INR,432.0,NaN,NaN,NaN,NaN,False,NaN
46493,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,L,...,Shipped,1,INR,493.0,NaN,NaN,NaN,NaN,False,NaN
46494,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,Kurta,L,...,Shipped,1,INR,458.0,NaN,NaN,NaN,NaN,False,NaN
56200,405-8605864-8021901,2022-05-04,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE1951,JNE1951-KR-155-XXL,Kurta,XXL,...,Shipped,1,INR,368.0,NaN,NaN,NaN,NaN,False,Easy Ship
56949,402-8651786-0683548,2022-05-04,Shipped,Amazon,Amazon.in,Expedited,JNE3690,JNE3690-TU-XL,Top,XL,...,Shipped,1,INR,487.0,NaN,NaN,NaN,NaN,False,NaN
58982,171-4691098-8489159,2022-05-06,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET183,SET183-KR-DH-M,Set,M,...,Shipped,1,INR,759.0,NaN,NaN,NaN,NaN,False,Easy Ship
61357,171-4552355-0255565,2022-05-07,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET324,SET324-KR-NP-XL,Set,XL,...,Shipped,1,INR,607.0,NaN,NaN,NaN,NaN,False,Easy Ship
61438,403-2857451-7335536,2022-05-07,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-S,Kurta,S,...,Shipped,1,INR,467.0,NaN,NaN,NaN,NaN,False,NaN
65568,405-1356730-8598722,2022-05-11,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET187,SET187-KR-DH-XL,Set,XL,...,Shipped,1,INR,699.0,NaN,NaN,NaN,NaN,False,Easy Ship
65639,407-4664354-2179554,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,Shipped,1,INR,666.0,NaN,NaN,NaN,NaN,False,NaN
65664,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3607,PJNE3607-KR-4XL,Kurta,4XL,...,Shipped,1,INR,869.0,NaN,NaN,NaN,NaN,False,NaN
65665,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3368,PJNE3368-KR-4XL,Kurta,4XL,...,Shipped,1,INR,869.0,NaN,NaN,NaN,NaN,False,NaN
65804,405-3420451-5230744,2022-05-11,Cancelled,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,Cancelled,0,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
76648,402-1049475-3611523,2022-05-20,Shipped,Amazon,Amazon.in,Expedited,JNE3739,JNE3739-KR-XXL,Kurta,XXL,...,Shipped,1,INR,459.0,NaN,NaN,NaN,NaN,False,NaN
79093,171-3257610-9237139,2022-05-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3365,JNE3365-KR-1052-A-L,Kurta,L,...,Shipped,1,INR,376.0,NaN,NaN,NaN,NaN,False,Easy Ship
93455,403-4249038-6582716,2022-06-02,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,M,...,Shipped,1,INR,735.0,NaN,NaN,NaN,NaN,False,Easy Ship
94860,403-5172380-9787567,2022-06-03,Shipped,Amazon,Amazon.in,Expedited,JNE3366,JNE3366-KR-1053-L,Kurta,L,...,Shipped,1,INR,376.0,NaN,NaN,NaN,NaN,False,NaN
96355,405-0340492-2359532,2022-06-04,Cancelled,Amazon,Amazon.in,Expedited,JNE3465,JNE3465-KR-L,Kurta,L,...,Unshipped,1,INR,491.0,NaN,NaN,NaN,NaN,False,NaN
96497,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,Kurta,L,...,Shipped,1,INR,486.0,NaN,NaN,NaN,NaN,False,NaN
96498,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET337,SET337-KR-NP-L,Set,L,...,Shipped,1,INR,874.0,NaN,NaN,NaN,NaN,False,NaN
96499,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET154,SET154-KR-NP-L,Set,L,...,Shipped,1,INR,832.0,NaN,NaN,NaN,NaN,False,NaN
106220,404-8924840-1497908,2022-06-11,Shipped,Amazon,Amazon.in,Expedited,JNE3837,JNE3837-KR-XXL,Kurta,XXL,...,Shipped,1,INR,533.0,NaN,UTTARAKHAND,248001.0,IN,False,NaN
113544,402-8673941-7883531,2022-06-16,Cancelled,Amazon,Amazon.in,Expedited,JNE3734,JNE3734-KR-XL,Kurta,XL,...,Cancelled,0,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
116027,403-3190636-2013146,2022-06-18,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-S,Set,S,...,Shipped,1,INR,792.0,NaN,NaN,NaN,NaN,False,Easy Ship

In [19]:
#replacing ship_city and ship_state to Unknown
df_cleaned[["ship_city", "ship_state"]] = df_cleaned[
    ["ship_city", "ship_state"]
].fillna("Unknown")

In [31]:
#filling null values in amount column with mean value
df_cleaned["amount"] = df_cleaned["amount"].fillna(df_cleaned["amount"].mean())

#filling null values in currency column with INR 
df_cleaned["currency"] = df_cleaned["currency"].fillna("INR")

#filling null values country with IN
df_cleaned["ship_country"] = df_cleaned["ship_country"].fillna("IN")

In [21]:
df_cleaned["courier_status"].value_counts()

courier_status
Shipped      109460
Unshipped      6681
Cancelled      5931
Name: count, dtype: int64

In [22]:
#null count in courier status column
df_cleaned["courier_status"].isnull().sum()

np.int64(6871)

In [23]:
#analysing courier status null values
display(df_cleaned[df_cleaned["courier_status"].isna()].head(5))

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b,fulfilled_by
2,171-7192082-3049169,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3461,JNE3461-KR-L,Kurta,L,...,NaN,0,INR,360.95,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN,False,Easy Ship
111,407-7115918-3595555,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-M,Western Dress,M,...,NaN,0,INR,724.76,VADAKARA,KERALA,673101.0,IN,False,Easy Ship
123,402-9332104-0945115,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3383,JNE3383-KR-A-M,Kurta,M,...,NaN,0,INR,416.19,GURGAON,HARYANA,122001.0,IN,False,Easy Ship
126,407-0339645-8708348,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-L,Western Dress,L,...,NaN,0,INR,724.76,VADAKARA,KERALA,673101.0,IN,False,Easy Ship
143,171-0068078-2649972,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-L,Western Dress,L,...,NaN,0,INR,724.76,VIJAY PORE,JAMMU & KASHMIR,184120.0,IN,False,Easy Ship

In [24]:
#extracting unique values from status column
statuses = []
print("before extracting : ",statuses)
for i in df_cleaned["status"].unique():
    statuses.append(i)
print("after extracting : ",statuses)

before extracting :  []
after extracting :  ['Shipped', 'Cancelled', 'Shipped - Delivered to Buyer', 'Shipped - Returned to Seller', 'Shipped - Rejected by Buyer', 'Pending', 'Shipped - Picked Up', 'Shipped - Returning to Seller', 'Shipped - Out for Delivery', 'Shipped - Lost in Transit', 'Shipping', 'Shipped - Damaged', 'Pending - Waiting for Pick Up']

In [25]:
#checking relation between courier status and status column

display(
    df_cleaned.loc[
        (df_cleaned["courier_status"].isna()) &
        (df_cleaned["status"].isin(statuses))
    ]
)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b,fulfilled_by
2,171-7192082-3049169,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3461,JNE3461-KR-L,Kurta,L,...,NaN,0,INR,360.950000,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN,False,Easy Ship
111,407-7115918-3595555,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-M,Western Dress,M,...,NaN,0,INR,724.760000,VADAKARA,KERALA,673101.0,IN,False,Easy Ship
123,402-9332104-0945115,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3383,JNE3383-KR-A-M,Kurta,M,...,NaN,0,INR,416.190000,GURGAON,HARYANA,122001.0,IN,False,Easy Ship
126,407-0339645-8708348,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-L,Western Dress,L,...,NaN,0,INR,724.760000,VADAKARA,KERALA,673101.0,IN,False,Easy Ship
143,171-0068078-2649972,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-L,Western Dress,L,...,NaN,0,INR,724.760000,VIJAY PORE,JAMMU & KASHMIR,184120.0,IN,False,Easy Ship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128790,405-3075434-2208303,2022-06-29,Cancelled,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-L,Western Dress,L,...,NaN,0,INR,648.545116,HYDERABAD,TELANGANA,500072.0,IN,False,Easy Ship
128795,403-1588348-3110758,2022-06-29,Cancelled,Merchant,Amazon.in,Standard,BTM041,BTM041-PP-XL,Bottom,XL,...,NaN,0,INR,315.240000,BENGALURU,KARNATAKA,560076.0,IN,False,Easy Ship
128904,407-8546052-4539504,2022-06-29,Cancelled,Merchant,Amazon.in,Standard,JNE3458,JNE3458-KR-M,Kurta,M,...,NaN,0,INR,361.900000,KOLKATA,WEST BENGAL,700028.0,IN,False,Easy Ship
128929,408-1755769-0715544,2022-06-29,Cancelled,Merchant,Amazon.in,Standard,JNE3294,JNE3294-KR-L,Kurta,L,...,NaN,0,INR,427.620000,SAKLESHPUR,KARNATAKA,573134.0,IN,False,Easy Ship
128940,407-6956275-3881912,2022-06-29,Cancelled,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-L,Western Dress,L,...,NaN,0,INR,648.545116,KALADHUNGI,UTTARAKHAND,263139.0,IN,False,Easy Ship

In [26]:
#replacing courier status column null values with according to status column
for status in statuses:
    mask = df_cleaned["courier_status"].isna() & df_cleaned["status"].eq(status)
    df_cleaned.loc[mask, "courier_status"] = status
print("Null values count in courier_status after replacing NaN values")
df_cleaned["courier_status"].isnull().sum()

Null values count in courier_status after replacing NaN values

np.int64(0)

In [32]:
display(
    df_cleaned.iloc[
        (df_cleaned["ship_city"]=="Unknown")
    ]
)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b,fulfilled_by
12713,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3567,JNE3567-KR-M,Kurta,M,...,Cancelled,0,INR,380.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
12714,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,Kurta,S,...,Cancelled,0,INR,380.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
18128,404-7506843-7913132,2022-04-12,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET350,SET350-KR-NP-L,Set,L,...,Shipped,1,INR,1299.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
23107,406-4079063-8291520,2022-04-15,Cancelled,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-XXL,Kurta,XXL,...,Unshipped,1,INR,399.000000,Unknown,Unknown,NaN,IN,False,NaN
24663,402-8628677-0457954,2022-04-16,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0003,J0003-SET-S,Set,S,...,Shipped,1,INR,654.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
29865,405-4927647-8064368,2022-04-19,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XS,Set,XS,...,Shipped,1,INR,1112.000000,Unknown,Unknown,NaN,IN,False,NaN
31829,402-4919636-4333150,2022-04-20,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE1233,JNE1233-BLUE-KR-031-XXXL,Kurta,3XL,...,Shipped,1,INR,376.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
34326,404-9229894-8608305,2022-04-21,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,Kurta,M,...,Shipped,1,INR,442.000000,Unknown,Unknown,NaN,IN,False,NaN
35293,407-4532637-8415521,2022-04-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,Kurta,S,...,Cancelled,0,INR,380.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
36729,402-0107720-7057168,2022-04-23,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,Shipped,1,INR,654.000000,Unknown,Unknown,NaN,IN,False,NaN
41367,406-4003386-8768363,2022-04-25,Shipped,Amazon,Amazon.in,Expedited,JNE3376,JNE3376-KR-M,Kurta,M,...,Shipped,1,INR,432.000000,Unknown,Unknown,NaN,IN,False,NaN
46493,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,L,...,Shipped,1,INR,493.000000,Unknown,Unknown,NaN,IN,False,NaN
46494,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,Kurta,L,...,Shipped,1,INR,458.000000,Unknown,Unknown,NaN,IN,False,NaN
56200,405-8605864-8021901,2022-05-04,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE1951,JNE1951-KR-155-XXL,Kurta,XXL,...,Shipped,1,INR,368.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
56949,402-8651786-0683548,2022-05-04,Shipped,Amazon,Amazon.in,Expedited,JNE3690,JNE3690-TU-XL,Top,XL,...,Shipped,1,INR,487.000000,Unknown,Unknown,NaN,IN,False,NaN
58982,171-4691098-8489159,2022-05-06,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET183,SET183-KR-DH-M,Set,M,...,Shipped,1,INR,759.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
61357,171-4552355-0255565,2022-05-07,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET324,SET324-KR-NP-XL,Set,XL,...,Shipped,1,INR,607.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
61438,403-2857451-7335536,2022-05-07,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-S,Kurta,S,...,Shipped,1,INR,467.000000,Unknown,Unknown,NaN,IN,False,NaN
65568,405-1356730-8598722,2022-05-11,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET187,SET187-KR-DH-XL,Set,XL,...,Shipped,1,INR,699.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
65639,407-4664354-2179554,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,Shipped,1,INR,666.000000,Unknown,Unknown,NaN,IN,False,NaN
65664,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3607,PJNE3607-KR-4XL,Kurta,4XL,...,Shipped,1,INR,869.000000,Unknown,Unknown,NaN,IN,False,NaN
65665,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3368,PJNE3368-KR-4XL,Kurta,4XL,...,Shipped,1,INR,869.000000,Unknown,Unknown,NaN,IN,False,NaN
65804,405-3420451-5230744,2022-05-11,Cancelled,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,Cancelled,0,INR,648.545116,Unknown,Unknown,NaN,IN,False,NaN
76648,402-1049475-3611523,2022-05-20,Shipped,Amazon,Amazon.in,Expedited,JNE3739,JNE3739-KR-XXL,Kurta,XXL,...,Shipped,1,INR,459.000000,Unknown,Unknown,NaN,IN,False,NaN
79093,171-3257610-9237139,2022-05-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3365,JNE3365-KR-1052-A-L,Kurta,L,...,Shipped,1,INR,376.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
93455,403-4249038-6582716,2022-06-02,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,M,...,Shipped,1,INR,735.000000,Unknown,Unknown,NaN,IN,False,Easy Ship
94860,403-5172380-9787567,2022-06-03,Shipped,Amazon,Amazon.in,Expedited,JNE3366,JNE3366-KR-1053-L,Kurta,L,...,Shipped,1,INR,376.000000,Unknown,Unknown,NaN,IN,False,NaN
96355,405-0340492-2359532,2022-06-04,Cancelled,Amazon,Amazon.in,Expedited,JNE3465,JNE3465-KR-L,Kurta,L,...,Unshipped,1,INR,491.000000,Unknown,Unknown,NaN,IN,False,NaN
96497,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,Kurta,L,...,Shipped,1,INR,486.000000,Unknown,Unknown,NaN,IN,False,NaN
96498,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET337,SET337-KR-NP-L,Set,L,...,Shipped,1,INR,874.000000,Unknown,Unknown,NaN,IN,False,NaN
96499,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET154,SET154-KR-NP-L,Set,L,...,Shipped,1,INR,832.000000,Unknown,Unknown,NaN,IN,False,NaN
106220,404-8924840-1497908,2022-06-11,Shipped,Amazon,Amazon.in,Expedited,JNE3837,JNE3837-KR-XXL,Kurta,XXL,...,Shipped,1,INR,533.000000,Unknown,UTTARAKHAND,248001.0,IN,False,NaN
113544,402-8673941-7883531,2022-06-16,Cancelled,Amazon,Amazon.in,Expedited,JNE3734,JNE3734-KR-XL,Kurta,XL,...,Cancelled,0,INR,648.545116,Unknown,Unknown,NaN,IN,False,NaN
116027,403-3190636-2013146,2022-06-18,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-S,Set,S,...,Shipped,1,INR,792.000000,Unknown,Unknown,NaN,IN,False,Easy Ship